import type { ChordTypeName, Extension, NoteClass } from '../types/chord';


export const NOTECLASS_TO_UI_STRING: Record<NoteClass, string> = {
  'C':  'C',
  'C#': 'C♯',
  'D':  'D',
  'D#': 'E♭',
  'E':  'E',
  'F':  'F',
  'F#': 'F♯',
  'G':  'G',
  'G#': 'G♯',
  'A':  'A',
  'A#': 'B♭',
  'B':  'B',
};

export const EXTENSION_TO_UI_STRING: Record<Extension, string> = {
  'b5':  '♭5',
  '#5':  '♯5',
  'b9':  '♭9',
  '#9':  '♯9',
  '#11': '♯11',
  'b13': '♭13',
  'alt': 'alt'
};

export const CHORDTYPENAME_TO_SETTINGS_UI_STRING: Record<ChordTypeName, string> = {
  'Major': 'Major',
  'minor': 'minor',
  'dim': '° (dim)',
  'aug': '+ (aug)',
  'sus2': 'sus2',
  'sus4': 'sus4',
  'M7': 'M7',
  'm7': 'm7',
  '7': '7',
  'mM7': 'mM7',
  'dim7': '°7 (dim7)',
  'm7b5': 'ø7 (Half-Diminished)',
  'augM7': '+M7 (augM7)',
  'aug7': '+7',
  '6': '6',
  'm6': 'm6',
  '6/9': '6/9',
  'M9': 'M9',
  'm9': 'm9',
  '9': '9',
  '11': '11',
  'M11': 'M11',
  'm11': 'm11',
  '13': '13',
  'M13': 'M13',
  'm13': 'm13',
  'add9': 'add9',
  'm(add9)': 'm(add9)',
  'add11': 'add11',
  'add13': 'add13',
  '7sus4': '7sus4',
};

export const CHORDTYPENAME_TO_DISPLAY_CHORD_UI_STRING: Record<ChordTypeName, string> = {
  'Major': 'Major',
  'minor': 'minor',
  'dim': '°',
  'aug': '+',
  'sus2': 'sus2',
  'sus4': 'sus4',
  'M7': 'M7',
  'm7': 'm7',
  '7': '7',
  'mM7': 'mM7',
  'dim7': '°7',
  'm7b5': 'Cø7',
  'augM7': '+M7',
  'aug7': '+7',
  '6': '6',
  'm6': 'm6',
  '6/9': '6/9',
  'M9': 'M9',
  'm9': 'm9',
  '9': '9',
  '11': '11',
  'M11': 'M11',
  'm11': 'm11',
  '13': '13',
  'M13': 'M13',
  'm13': 'm13',
  'add9': 'add9',
  'm(add9)': 'm(add9)',
  'add11': 'add11',
  'add13': 'add13',
  '7sus4': '7sus4',
};

